### ISSUE TITLE
Toggle dev-mode

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/useuses#32]
Enabling dev-mode would extend file-lookup. It would make the distinction between looking up minified files, and their regular non-minified equivalent.

**Comment by dustinwalker** [comment]
I could be reading this completely wrong but would this enable a sort of sourcemaps like ability for debugging? 

For my needs I really like the simplicity of this solution as part of our Gulp workflow vs something like webpack but was just trying to figure out how to get that ability. Thanks!

**Comment by RWOverdijk** [comment]
@dustinwalker The idea I had was to automatically collect the assets using the `.min.js` extension for production builds, and using the `.js` extension for development builds. I wasn't sure if this would add any value so I didn't build it.

**Comment by dustinwalker** [comment]
That makes sense. Thanks for the follow up. I'll open another issue that can be tagged as a question on wether it's possible to track which file is the source when looking at the javascript console. Thanks again.

**Comment by RWOverdijk** [comment]
And thank you for the question. Cheers! :)
