### ISSUE TITLE
Useuses forget to skip a line which can cause a bug when minfying js

### ISSUE THREAD

**Issue by Scrunshes** [SpoonX/useuses#43]
Useuses forget to skip a line which can cause a bug when minfying js.

````js
/* First lib */
myBigChunkOfCode(); /* Second lib
with long comments ! 
very long ones */
MyOtherBigChunkOfCode();
````

This code when parsed throught gulp-uglify result in  an error : `Unexpected token: name (The name of the new line without // or /*)`
Because Useuses forgets to skip a line between files copied.
~~I think~~ We can consider this as a bug.

**Comment by RWOverdijk** [comment]
@Scrunshes Could you elaborate this a bit more? Perhaps supply a working (so, failing) test case?

**Comment by Scrunshes** [comment]
Okay
Steps : 
1. Create a gulpfile where you use useuses to resolve dependencies in the main.js file
2. @uses these libraries in order : jquery.min.js, rivets.min.js
3. Use gulp-uglify on the main.js file created with the deps
4. Look at the file you should see that useuses `forgot to jump` a line
