### ISSUE TITLE
Way to load all file from a folder

### ISSUE THREAD

**Issue by Scrunshes** [SpoonX/useuses#44]
It would be very useful to be able to do like : 
````js
/**
 * 
 * @description :: load all file from the directory
 *
 * @uses directory/*
 *
 * @description :: load all file from the directory with `.js`
 *
 * @uses directory/*.js
 *
 * 
 */
````
And basically it.

**Comment by RWOverdijk** [comment]
@Scrunshes I've actually considered this and figured it's not worth it. This would only make sense if:

* You actually use everything inside of that directory
* The directory contains functions that all function on their own, with no dependencies upon each other.

I do agree that this might be a fun thing to add, but I'm not sure if this is something that would (should) be used. I personally prefer specifying the dependencies explicitly in a `main.js` or `index.js`.

**Comment by Scrunshes** [comment]
It's clear that cases of use are very peculiar. May not worth the time of coding this.
